ProyectoAAPolo/AAPolo/Controllers/ClubController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class ClubController : ClassHelper
    {
        // GET: Club
        public ActionResult Index()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public PartialViewResult Listado(int Cod_CategoriaClub = 0, int Cod_Club = 0, string Nombre = "")
        {
            List<Club> lClub = new ClubSM().BuscaClub(Cod_CategoriaClub, Cod_Club, Nombre, 0);
            return PartialView(lClub);
        }

        public PartialViewResult _SelectTipoCategoriaClub()
        {
            try
            {
                return PartialView(new ClubSM().BuscarCategoriaClub());
            }
            catch (Exception)
            {
                return PartialView(new List<CategoriaClub>());
            }
        }

        public ActionResult CrearClub()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public ActionResult EditarClub(int Codigo = 0)
        {
            if (Codigo == 0)
                return RedirectToAction("Index");

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            try
            {
                return View(new ClubSM().BuscaClub(0, Codigo, "", 0).FirstOrDefault());
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }

        }

        public JsonResult _CrearClub(Club obj)
        {

            ResultadoTransaccion result = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos."
            };

            try
            {
                if (!String.IsNullOrEmpty(obj.strFechaFundacion))
                {
                    int Dia = Convert.ToInt32(obj.strFechaFundacion.Split('-')[0]),
                        Mes = Convert.ToInt32(obj.strFechaFundacion.Split('-')[1]),
                        Anio = Convert.ToInt32(obj.strFechaFundacion.Split('-')[2]);
                    obj.FechaFundacion = new DateTime(Anio, Mes, Dia);
                }
                else {
                    obj.FechaFundacion = new DateTime(1753, 1, 1);
                }

                if (obj.Imagen != null)
                {
                    obj.UrlImagen = GuardarImagen(obj.Imagen);
                }
                else
                {
                    obj.UrlImagen = "";
                }

                result = new ClubSM().GuardarClub(obj);
            }
            catch (Exception e)
            {
                result.MensajeError = e.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public JsonResult CambiarEstadoClub(int Codigo, int EstadoClub)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new ClubSM().CambiarEstadoClub(Codigo, EstadoClub);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstadoDestacadoClub(int Codigo, int EstadoDestacadoClub)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new ClubSM().CambiarEstadoDestacadoClub(Codigo, EstadoDestacadoClub);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _Contacto(TipoContacto obj, Contacto contacto = null)
        {
            if (contacto == null)
            {
                contacto = new Contacto() { TipoContacto = obj };
            }
            else
            {
                contacto.TipoContacto = obj;
                if (contacto.Nombre.Equals(contacto.TipoContacto.Nombre) || String.IsNullOrEmpty(contacto.Nombre)) {
                    if (obj.Codigo == ConfiguracionAPP.TipoContacto_Email)
                        contacto.Nombre = "noinformado@noinformado.com";
                    else
                        contacto.Nombre = "No informado";
                }
            }

            return PartialView(contacto);
        }

        public PartialViewResult _Domicilio(TipoDomicilio obj, Domicilio domicilio = null)
        {

            if (domicilio == null)
            {
                domicilio = new Domicilio()
                {
                    tipoDomicilio = obj
                };
            }
            else
            {
                domicilio.tipoDomicilio = obj;
            }

            return PartialView(domicilio);
        }

        public PartialViewResult _SelectPais(int Cod_Pais = 0)
        {
            try
            {
                ViewBag.Cod_Pais = Cod_Pais;
                return PartialView(new PersonaSM().BuscarPais());
            }
            catch (Exception e)
            {
                return PartialView(new List<Pais>());
            }
        }

        public PartialViewResult _SelectProvincia(int Codigo = 0, int Cod_Provincia = 0)
        {
            try
            {
                ViewBag.Cod_Provincia = Cod_Provincia;
                return PartialView(new PersonaSM().BuscarProvincia(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Provincia>());
            }
        }

        public PartialViewResult _SelectMunicipio(int Codigo = 0, int Cod_Municipio = 0)
        {
            try
            {
                ViewBag.Cod_Municipio = Cod_Municipio;
                return PartialView(new PersonaSM().BuscarMunicipio(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Municipio>());
            }
        }

        public PartialViewResult _SelectPersona()
        {
            try
            {
                return PartialView(new PersonaSM().BuscaJugador(new Persona() { Codigo = 0 }));
            }
            catch (Exception e)
            {
                ViewBag.ErrorCatch = e.Message;
                return PartialView(new List<Persona>());
            }
        }

        public PartialViewResult _BuscarUsuario(string Cadena)
        {
            try
            {
                return PartialView(new PersonaSM().BuscaJugadorResumen(0, Cadena, 0, 0, -1, 0));
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return PartialView(new List<Persona>());
            }
        }



    }
}

ProyectoAAPolo/AAPolo/Controllers/TorneoController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class TorneoController : ClassHelper
    {
        #region Torneo
        // GET: Torneo
        public ActionResult Index()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public PartialViewResult _Listado()
        {
            try
            {
                return PartialView(new TorneoSM().BuscarTorneo(0, 0, 0, false));
            }
            catch (Exception)
            {
                return PartialView(new List<Torneo>());
            }
        }

        public ActionResult CrearTorneo()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public ActionResult EditarTorneo(int Codigo = 0)
        {
            if (Codigo == 0)
                return RedirectToAction("Index");

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            try
            {
                Torneo t = new TorneoSM().BuscarTorneo(Codigo, 0, 0, false).FirstOrDefault();
                /*if (!t.Url_Imagen.Equals("")) {
                    byte[] bytes = System.IO.File.ReadAllBytes(Server.MapPath(t.Url_Imagen));
                    t.Imagen = (HttpPostedFileBase)new MemoryPostedFile(bytes, t.Url_Imagen.Split('/').LastOrDefault());
                }*/
                return View(t);
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }



        }

        public JsonResult GuardarTorneo(Torneo obj)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                if (obj.Codigo == 0)
                {
                    obj.Url_Imagen = GuardarImagen(obj.Imagen);
                }
                else if (obj.Imagen != null)
                {
                    obj.Url_Imagen = GuardarImagen(obj.Imagen);
                }
                else if (obj.ArchivoDocumento != null)
                {
                    obj.Url_ArchivoDocumento = GuardarImagen(obj.ArchivoDocumento);
                }

                obj.UsuarioAlta = DatosUsuario();

                int Dia = Convert.ToInt32(obj.strFechaInicio.Split('/')[0]),
                    Mes = Convert.ToInt32(obj.strFechaInicio.Split('/')[1]),
                    Anio = Convert.ToInt32(obj.strFechaInicio.Split('/')[2]);
                obj.FechaInicio = new DateTime(Anio, Mes, Dia);

                Dia = Convert.ToInt32(obj.strFechaInicioInscripcion.Split('/')[0]);
                Mes = Convert.ToInt32(obj.strFechaInicioInscripcion.Split('/')[1]);
                Anio = Convert.ToInt32(obj.strFechaInicioInscripcion.Split('/')[2]);
                obj.FechaInicioInscripcion = new DateTime(Anio, Mes, Dia);

                Dia = Convert.ToInt32(obj.strFechaFinInscripcion.Split('/')[0]);
                Mes = Convert.ToInt32(obj.strFechaFinInscripcion.Split('/')[1]);
                Anio = Convert.ToInt32(obj.strFechaFinInscripcion.Split('/')[2]);
                obj.FechaFinInscripcion = new DateTime(Anio, Mes, Dia);

                resul = new TorneoSM().GuardarTorneo(obj);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _SelectTipoTorneo()
        {
            try
            {
                return PartialView(new TorneoSM().BuscarTipoTorneo());
            }
            catch (Exception)
            {
                return PartialView(new List<TipoTorneo>());
            }
        }

        [ChildActionOnly]
        public PartialViewResult _SelectTorneoActivo()
        {
            try
            {
                return PartialView(new TorneoSM().BuscarTorneo(0, 0, 0, true));
            }
            catch (Exception)
            {
                return PartialView(new List<Torneo>());
            }
        }

        public PartialViewResult _SelectCategoriaHandicapTorneo()
        {
            try
            {
                return PartialView(new TorneoSM().BuscarCategoriaHandicapTorneo());
            }
            catch (Exception)
            {
                return PartialView(new List<CategoriaHandicap>());
            }
        }

        public PartialViewResult _SelectCodigoProducto(int CodigoProducto = 0)
        {
            try
            {
                ViewBag.CodigoProducto = CodigoProducto;
                return PartialView(new TorneoSM().BuscarProductoTorneo(true));
            }
            catch (Exception)
            {
                return PartialView(new List<ProductoTorneo>());
            }
        }

        public JsonResult CambiarEstadoTorneo(int Codigo, int EstadoTorneo)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new TorneoSM().CambiarEstadoTorneo(Codigo, EstadoTorneo);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _HtmlModalCrearCodigoProducto()
        {
            return PartialView();
        }

        public JsonResult GuardarCodigoProducto(ProductoTorneo obj)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            if (!String.IsNullOrEmpty(obj.Nombre))
                resul = new TorneoSM().GuardarCodigoProducto(obj);

            if (resul.EsSatisfactorio)
            {
                this.ControllerContext.Controller.ViewBag.CodigoProducto = resul.CodigoResultado;
                resul.Vista = RenderRazorViewToString(this.ControllerContext, "_SelectCodigoProducto", new TorneoSM().BuscarProductoTorneo(true));
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Fixture

        public ActionResult FixtureTorneo(int Codigo = 0, bool Actualizar = false)
        {

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            if (Codigo == 0)
                return RedirectToAction("Index");

            List<Zona> lZona = new TorneoSM().BuscarZonaTorneo(Codigo, false, 0);

            if (lZona != null && lZona.Count() > 0 && Actualizar == false)
                return RedirectToAction("AsignarEquipoZona", new { Codigo = Codigo });

            List<Equipo> lEquipo = new ReporteSM().BuscarReporteEquipo(0, Codigo, "", 0);
            int CantEquipo = lEquipo.Where(x => x.detallePago.estado.Codigo == ConfiguracionAPP.Pago_Satisfactorio).Count(),
                SugeridoZona3 = 0,
                SugeridoZona4 = 0,
                resto = 0,
                TotalZona = 0;
            bool Continuar;

            if (CantEquipo >= 33 && CantEquipo <= 64)
            {
                if (CantEquipo / 3 <= 16 || Convert.ToDecimal(CantEquipo / 4) <= 16)
                {
                    if (CantEquipo % 3 == 0 && !(Enumerable.Contains(new int[] { 5, 6, 9, 10 }, (CantEquipo / 3))) && (CantEquipo / 3) <= 16 && TotalZona <= 16)
                    {
                        SugeridoZona3 = CantEquipo / 3;
                        SugeridoZona4 = 0;
                    }
                    else if (CantEquipo % 4 == 0 && !(Enumerable.Contains(new int[] { 5, 6, 9, 10 }, (CantEquipo / 4))) && (CantEquipo / 4) <= 16 && TotalZona <= 16)
                    {
                        SugeridoZona4 = CantEquipo / 4;
                        SugeridoZona3 = 0;
                    }
                    else
                    {
                        resto = CantEquipo % 4;
                        CantEquipo -= resto;
                        Continuar = true;
                        while (Continuar && CantEquipo > 0)
                        {
                            TotalZona = (CantEquipo / 4) + (resto / 3);
                            if ((CantEquipo) % 4 == 0 && (resto % 3 == 0) && !(Enumerable.Contains(new int[] { 5, 6, 9, 10 }, TotalZona)) && TotalZona <= 16)
                            {
                                SugeridoZona4 = (CantEquipo / 4);
                                SugeridoZona3 = (resto / 3);
                                Continuar = false;
                            }
                            else
                            {
                                if ((CantEquipo) % 4 > 0)
                                {
                                    resto += (CantEquipo) % 4;
                                    CantEquipo -= (CantEquipo) % 4;
                                }
                                else
                                {
                                    resto += 1;
                                    CantEquipo -= 1;
                                }

                            }
                        }

ProyectoAAPolo/AAPolo/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html class="no-js" lang="">
<head prefix="og: http://ogp.me/ns#">
    <!-- Google Tag Manager -->
    <script>(function (w, d, s, l, i) { w[l] = w[l] || []; w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' }); var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f); })(window, document, 'script', 'dataLayer', 'GTM-W7WJ8TR');</script>
    <!-- End Google Tag Manager -->

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Asociación Argentina de Polo</title>
    <meta name="description" content="Sitio web oficial de la AAP.">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, viewport-fit=cover">
    <meta property="og:title" content="Asociación Argentina de Polo">
    <meta property="og:url" @*content="http://aapolo.com"*@>
    <meta property="og:description" content="Sitio web oficial de la AAP.">
    <meta property="og:image" content="@Url.Content("~/Content/img/share-img.jpg")">
    <meta property="og:type" content="article">
    <meta name="theme-color" content="#2065a5">
    <meta name="msapplication-TileColor" content="#2065a5">

    @*<link rel="manifest" href="site.webmanifest">*@
    <link rel="apple-touch-icon" href="icon.png">
    <!-- Place favicon.ico in the root directory -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,900" rel="stylesheet">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/summernote.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/css/normalize.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/animate.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/icons.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/select2.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/datepicker.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/css/main.css")">

    <style>
        .wow {
            visibility: hidden;
        }
    </style>
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W7WJ8TR" height="0" width="0" style="display:none; visibility:hidden;"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!--[if lte IE 9]>
        <p class="browserupgrade">Estás usando un navegador <strong>desactualizado</strong>. Por favor, <a href="https://browsehappy.com/">actualiza tu navegador</a> para una mejor y más segura experiencia.</p>
    <![endif]-->

    <div class="overlay-nav"></div>
    <header>
        <a href="@Url.Action("Index", "Home")" class="logo">
            <img src="@Url.Content("~/Content/img/logo.png")" alt="AAP">
            <h3 class="title-admin-head">Panel de administración</h3>
        </a>

        <div class="header-right">
            <div class="user-top">
                <a href="javascript:void(0);" class="dropdown">
                    <div class="user-pic" style="background-image: url('@Url.Content("~/Content/img/avatars/avatar-user1.png")')"></div>
                    <h4>Administrador</h4>
                </a>
                <ul>
                    @*<li><a href="javascript:void(0);" data-icon="&#xe005;">Soporte</a></li>*@
                    <li><a href="@Url.Action("CerrarSession","Home")" data-icon="&#xe036;">Cerrar sesión</a></li>
                </ul>
            </div>
        </div>

        <div class="burger open-nav">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </header>

    <aside class="admin-nav">
        <div class="user-top show-mobile">
            <a href="javascript:void(0);" class="dropdown">
                <div class="user-pic" style="background-image: url('@Url.Content("~/Content/img/avatars/avatar-user1.png")')"></div>
                <h4>Juan Carlos</h4>
            </a>
            <ul>
                <li><a href="javascript:void(0);" data-icon="&#xe005;">Soporte</a></li>
                <li><a href="@Url.Action("Index","Home")" data-icon="&#xe036;">Cerrar sesión</a></li>
            </ul>
        </div>

        <ul>
            <li id="aLiJugador"><a href="@Url.Action("Index","Jugador")" onclick="javascript:localStorage.setItem('opMenu','aLiJugador')"><i class="icon-user"></i> Jugadores</a></li>
            <li id="aLiClub"><a href="@Url.Action("Index","Club")" onclick="javascript:localStorage.setItem('opMenu','aLiClub')"><i class="icon-flag"></i> Clubes</a></li>
            @*<li><a href="canchas.html"><i class="icon-location"></i> Canchas</a></li>
        <li><a href="eventos.html"><i class="icon-calendar"></i> Eventos</a></li>*@
            <li id="aliReferee"><a href="@Url.Action("Index","Referee")" onclick="javascript:localStorage.setItem('opMenu','aliReferee')"><i class="icon-flag"></i>Referees</a></li>
            <li id="aLiTorneo"><a href="@Url.Action("Index","Torneo")" onclick="javascript:localStorage.setItem('opMenu','aLiTorneo')"><i class="icon-trophy"></i> Torneos</a></li>
            @*<li><a href="partidos2.html"><i class="icon-stopwatch"></i> Partidos</a></li>*@
            <li id="aLiNoticia"><a href="@Url.Action("Index","Noticia")" onclick="javascript:localStorage.setItem('opMenu','aLiNoticia')"><i class="icon-document"></i> Noticias</a></li>

            <li @* class="aLiCommunity"*@>
                <a href="javascript:void(0);" class="submenu"><i class="icon-star"></i>Community</a>
                <ul id="aLiCommunity">
                    <li id="aLiCommunityBeneficios" class="aLiCommunityBeneficios"><a href="@Url.Action("Index","Beneficio")">Beneficios</a></li>
                    @*<li id="aLiTemporadaPuntos" class="aLiTemporadaPuntos"><a href="@Url.Action("Index","Temporada")">Puntos Clubes</a></li>*@
                </ul>
            </li>
            <li id="liNotificacion"><a href="@Url.Action("Index","Notificacion")" onclick="javascript:localStorage.setItem('opMenu','liTribunalDisciplina')"><i class="icon-warning"></i> Notificaciones y mensajes</a></li>
            <li id="liTribunalDisciplina"><a href="@Url.Action("Index","Sancion")" onclick="javascript:localStorage.setItem('opMenu','liTribunalDisciplina')"><i class="icon-broadcast"></i>Tribunal de disciplina</a></li>

            @*<li><a href="javascript:void(0);"><i class="icon-bookmark"></i> Biblioteca</a></li>
        <li><a href="notificaciones.html"><i class="icon-warning"></i> Notificaciones y mensajes</a></li>
        <li><a href="comunicados.html"><i class="icon-message"></i> Comunicados</a></li></li>
        <li><a href="polo-video.html"><i class="icon-media-play"></i> Polo Video</a></li>*@
            <li id="liReporteClub"><a href="@Url.Action("ReporteClub","Reporte")" onclick="javascript:localStorage.setItem('opMenu','liReporteClub')"><i class="icon-flag"></i>Reporte de pago de afiliaciones</a></li>
            <li id="liReportePagoHandicap"><a href="@Url.Action("ReporteHandicap","Reporte")" onclick="javascript:localStorage.setItem('opMenu','liReportePagoHandicap')"><i class="icon-flag"></i>Reporte de pago de Handicaps</a></li>
            <li id="liReporteTorneo"><a href="@Url.Action("ReporteGeneralInscripcionTorneo","Reporte")" onclick="javascript:localStorage.setItem('opMenu','liReporteTorneo')"><i class="icon-flag"></i>Reporte de pago de inscripciones</a></li>
        </ul>
    </aside>

    <div class="admin-container">
        @RenderBody()
    </div>

    <!-- Add your site or application content here -->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryAjax")
    @Scripts.Render("~/bundles/jqueryval")


    <script src="@Url.Content("~/Scripts/modernizr-3.5.0.min.js")"></script>
    @*<script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>*@
    <script src="@Url.Content("~/Scripts/jquery.mask.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins.js")"></script>
    <script src="@Url.Content("~/Scripts/select2.full.min.js")"></script>
    <script src="@Url.Content("~/Scripts/vivus.min.js")"></script>
    <script src="@Url.Content("~/Scripts/wow.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.easing.1.3.js")"></script>
    <script src="@Url.Content("~/Scripts/tooltip.js")"></script>
    <script src="@Url.Content("~/Scripts/slick.min.js")"></script>
    <script src="@Url.Content("~/Scripts/picker.js")"></script>
    <script src="@Url.Content("~/Scripts/picker.date.js")"></script>
    <script src="@Url.Content("~/Scripts/main.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/summernote.js")"></script>
    <script src="@Url.Content("~/Scripts/summernote-es-ES.js")"></script>

    <script src="@Url.Content("~/Scripts/Generico.js")"></script>

    <script>
        // ACTIVO PLUGIN SELECT2
        $(document).ready(function () {
            $('.select2-basic').select2();

            $('.select2-tags').select2(
                {
                    tags: true
                }
            );

        });

    </script>

    @RenderSection("scripts", required: false)

    <script>

        $(document).ready(function(){
            $('.ulItemMenu li').removeClass('current');
            if (localStorage.getItem('opMenu') == '' || localStorage.getItem('opMenu') == null) {
                if ('@Request.IsAuthenticated.ToString().ToLower()' != 'false') {
                    $('#aLiJugador').addClass('current');
                    localStorage.setItem('opMenu', 'aLiJugador');

                }
            } else {
                $('#' + localStorage.getItem('opMenu')).addClass('current');
            }
        });
    </script>

</body>
</html>