ProyectoAAPolo/AAPolo/Controllers/ClubController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class ClubController : ClassHelper
    {
        // GET: Club
        public ActionResult Index()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public PartialViewResult Listado(int Cod_CategoriaClub = 0, int Cod_Club = 0, string Nombre = "")
        {
            List<Club> lClub = new ClubSM().BuscaClub(Cod_CategoriaClub, Cod_Club, Nombre, 0);
            return PartialView(lClub);
        }

        public PartialViewResult _SelectTipoCategoriaClub()
        {
            try
            {
                return PartialView(new ClubSM().BuscarCategoriaClub());
            }
            catch (Exception)
            {
                return PartialView(new List<CategoriaClub>());
            }
        }

        public ActionResult CrearClub()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public ActionResult EditarClub(int Codigo = 0)
        {
            if (Codigo == 0)
                return RedirectToAction("Index");

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            try
            {
                return View(new ClubSM().BuscaClub(0, Codigo, "", 0).FirstOrDefault());
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }

        }

        public JsonResult _CrearClub(Club obj)
        {

            ResultadoTransaccion result = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos."
            };

            try
            {
                if (!String.IsNullOrEmpty(obj.strFechaFundacion))
                {
                    int Dia = Convert.ToInt32(obj.strFechaFundacion.Split('-')[0]),
                        Mes = Convert.ToInt32(obj.strFechaFundacion.Split('-')[1]),
                        Anio = Convert.ToInt32(obj.strFechaFundacion.Split('-')[2]);
                    obj.FechaFundacion = new DateTime(Anio, Mes, Dia);
                }
                else {
                    obj.FechaFundacion = new DateTime(1753, 1, 1);
                }

                if (obj.Imagen != null)
                {
                    obj.UrlImagen = GuardarImagen(obj.Imagen);
                }
                else
                {
                    obj.UrlImagen = "";
                }

                result = new ClubSM().GuardarClub(obj);
            }
            catch (Exception e)
            {
                result.MensajeError = e.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public JsonResult CambiarEstadoClub(int Codigo, int EstadoClub)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new ClubSM().CambiarEstadoClub(Codigo, EstadoClub);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstadoDestacadoClub(int Codigo, int EstadoDestacadoClub)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new ClubSM().CambiarEstadoDestacadoClub(Codigo, EstadoDestacadoClub);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _Contacto(TipoContacto obj, Contacto contacto = null)
        {
            if (contacto == null)
            {
                contacto = new Contacto() { TipoContacto = obj };
            }
            else
            {
                contacto.TipoContacto = obj;
                if (contacto.Nombre.Equals(contacto.TipoContacto.Nombre) || String.IsNullOrEmpty(contacto.Nombre)) {
                    if (obj.Codigo == ConfiguracionAPP.TipoContacto_Email)
                        contacto.Nombre = "noinformado@noinformado.com";
                    else
                        contacto.Nombre = "No informado";
                }
            }

            return PartialView(contacto);
        }

        public PartialViewResult _Domicilio(TipoDomicilio obj, Domicilio domicilio = null)
        {

            if (domicilio == null)
            {
                domicilio = new Domicilio()
                {
                    tipoDomicilio = obj
                };
            }
            else
            {
                domicilio.tipoDomicilio = obj;
            }

            return PartialView(domicilio);
        }

        public PartialViewResult _SelectPais(int Cod_Pais = 0)
        {
            try
            {
                ViewBag.Cod_Pais = Cod_Pais;
                return PartialView(new PersonaSM().BuscarPais());
            }
            catch (Exception e)
            {
                return PartialView(new List<Pais>());
            }
        }

        public PartialViewResult _SelectProvincia(int Codigo = 0, int Cod_Provincia = 0)
        {
            try
            {
                ViewBag.Cod_Provincia = Cod_Provincia;
                return PartialView(new PersonaSM().BuscarProvincia(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Provincia>());
            }
        }

        public PartialViewResult _SelectMunicipio(int Codigo = 0, int Cod_Municipio = 0)
        {
            try
            {
                ViewBag.Cod_Municipio = Cod_Municipio;
                return PartialView(new PersonaSM().BuscarMunicipio(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Municipio>());
            }
        }

        public PartialViewResult _SelectPersona()
        {
            try
            {
                return PartialView(new PersonaSM().BuscaJugador(new Persona() { Codigo = 0 }));
            }
            catch (Exception e)
            {
                ViewBag.ErrorCatch = e.Message;
                return PartialView(new List<Persona>());
            }
        }

        public PartialViewResult _BuscarUsuario(string Cadena)
        {
            try
            {
                return PartialView(new PersonaSM().BuscaJugadorResumen(0, Cadena, 0, 0, -1, 0));
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return PartialView(new List<Persona>());
            }
        }



    }
}

ProyectoAAPolo/AAPolo/Controllers/temporadaController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class TemporadaController : ClassHelper
    {
        // GET: PuntajeCLub
        public ActionResult Index()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public PartialViewResult _Listado() {
            try
            {
                return PartialView(new TemporadaSM().BuscarTemporadaPuntajeXClub(0,0,0,0));
            }
            catch (Exception)
            {
                return PartialView(new List<PuntoXClub>());
            }
        }

        public ActionResult CrearRegistroPuntaje() {

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public ActionResult EditarRegistroPuntaje(int Codigo = 0)
        {
            if (Codigo == 0)
                return RedirectToAction("Index");

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            try
            {
                return View(new TemporadaSM().BuscarTemporadaPuntajeXClub(Codigo, 0, 0, 0).FirstOrDefault());
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }
        }

        public PartialViewResult _SelectCategiriaAccion(int Codigo = 0) {
            try
            {
                ViewBag.Codigo = Codigo;
                return PartialView(new TemporadaSM().BuscarCategoriaAccion());
            }
            catch (Exception)
            {
                return PartialView(new List<CategoriaAccion>());
            }
        }

        public PartialViewResult _SelectTemporada(int Codigo = 0)
        {
            try
            {
                ViewBag.Codigo = Codigo;
                return PartialView(new TemporadaSM().BuscarTemporada());
            }
            catch (Exception)
            {
                return PartialView(new List<Temporada>());
            }
        }

        public PartialViewResult _BuscarClub(string Nombre) {
            try
            {
                return PartialView(new ClubSM().BuscaClub(0, 0, Nombre, 0));
            }
            catch (Exception)
            {
                return PartialView(new List<Club>());
            }
        }

        public JsonResult GuardarTemporada(PuntoXClub obj) {
            ResultadoTransaccion result = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos."
            };

            try
            {
                if (obj.Codigo < 1)
                {
                    result.Mensaje = "Disculpe, debe seleccionar un club.";
                }
                else if (obj.Puntos < 1)
                {
                    result.Mensaje = "Disculpe, debe ingresar la cantidad de puntos.";
                }
                else if (obj.CategoriaAccion.Codigo < 1)
                {
                    result.Mensaje = "Disculpe, debe seleccionar una categoría de acción.";
                }
                else if (obj.Temporada.Codigo < 1)
                {
                    result.Mensaje = "Disculpe, debe seleccionar temporada.";
                }
                else if (String.IsNullOrEmpty(obj.Accion))
                {
                    result.Mensaje = "Disculpe, debe ingresar la acción realizada.";
                }
                else if (String.IsNullOrEmpty(obj.Premio))
                {
                    result.Mensaje = "Disculpe, debe ingresar premio camnjeado.";
                }
                else if (obj.ImagenEvidencia == null && obj.Cod_Canje == 0)
                {
                    result.Mensaje = "Disculpe, debe ingresar una imagen de portada.";
                }
                else {

                    if (obj.ImagenEvidencia != null)
                        obj.UrlImagenEvidencia = GuardarImagen(obj.ImagenEvidencia);
                    else
                        obj.UrlImagenEvidencia = "";

                    result = new TemporadaSM().GuardarTemporada(obj, DatosUsuario().Codigo);
                }
            }
            catch (Exception e)
            {
                result.MensajeError = e.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstadoTemporada(int Codigo, int EstadoTemporada)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new TemporadaSM().CambiarEstadoTemporada(Codigo, EstadoTemporada);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

    }
}

ProyectoAAPolo/AAPolo/Views/Temporada/CrearRegistroPuntaje.cshtml
@model AAPolo.Entities.PuntoXClub

@{

    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="col-md-12">
    <div class="panel panel-profile">
        <div class="panel-body">
            <h1 class="title-admin pull-left">Cargar Puntos Clubes</h1>
            <a href="javascript:void(0);" class="btn btn-lightblue pull-right m-t-0" data-modal="confirmarSalir"><i class="icon-arrow-thin-left"></i> Volver al listado</a>

            <div class="clearfix"></div>

            @using (Ajax.BeginForm("GuardarTemporada", "Temporada", null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "fnSuccessProcesar", OnFailure = "fnFailProcesar" }, new { @id = "RegistroForm", @class = "form-default FormFile" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row clearfix m-t-20">
                    <div class="col-md-3">
                        @Html.HiddenFor(model => model.Codigo)
                        <label for="presidente">Club Asociado</label>
                        <div class="input-search">
                            <ul id="txtNombreClub"></ul>
                            <a href="javascript:void(0);" class="btn btn-lightblue text-center single-icon" data-modal="buscarGenerico"><i class="icon-search"></i></a>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <label for="presidente">Cantidad de Puntos</label>
                        @Html.TextBoxFor(model => model.Puntos)
                    </div>

                    <div class="col-md-2">
                        <label for="tipo">Categoria de acción</label>
                        <select name="@Html.NameFor(model => model.CategoriaAccion.Codigo)" id="@Html.IdFor(model => model.CategoriaAccion.Codigo)" class="select2-basic">
                            @Html.Action("_SelectCategiriaAccion", "Temporada")
                        </select>
                    </div>

                    <div class="col-md-2">
                        <label for="tipo">Temporada</label>
                        <select name="@Html.NameFor(model => model.Temporada.Codigo)" id="@Html.IdFor(model => model.Temporada.Codigo)" class="select2-basic">
                            @Html.Action("_SelectTemporada", "Temporada")
                        </select>
                    </div>

                    <div class="col-md-2">
                        <label for="AnioTemporadas">Año de temporada</label>
                        <select name="@Html.NameFor(model => model.AnioTemporada)" id="@Html.IdFor(model => model.AnioTemporada)" class="select2-basic">
                            <option value="0" disabled>Seleccione año de temporada</option>
                            <option value="@DateTime.Now.Year" selected>@DateTime.Now.Year</option>
                            <option value="@(DateTime.Now.Year-1)">@(DateTime.Now.Year - 1)</option>
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label for="Accion">Acción</label>
                        @Html.TextAreaFor(model => model.Accion, new { @placeholder = "max. 280 caracteres", @style = "height: 200px;" })
                        <p id="msjCaracter" style="color:red"><span id="cantCaracter">280</span> caracteres</p>
                    </div>

                    <div class="col-md-6">
                        <label for="Premio">Premio que canjeo</label>
                        @Html.TextAreaFor(model => model.Premio, new { @placeholder = "max. 280 caracteres", @style = "height: 200px;" })
                        <p id="msjCaracter" style="color:red"><span id="cantCaracter">280</span> caracteres</p>
                    </div>

                    <div class="col-md-12">
                        <label for="inicio">Imagen de evidencia</label>

                        <label class="btn btn-lightblue m-t-0" for="ImagenEvidencia" style="margin-top: 20px !important;"><i class="icon-browser-upload"></i>&nbsp; Subir imagen de portada</label>
                        @Html.TextBoxFor(model => model.ImagenEvidencia, new { @class = "file-uploader img-previewer", @type = "file", @accept = "image/*" })
                        <div class="img-preview">
                            <img src="" alt="">
                            <a href="javascript:void(0);" class="delete-img"><i class="icon-cross"></i></a>
                        </div>
                        <span class="file-name"></span>
                    </div>

                    <div class="col-md-4 col-md-offset-8">
                        <button type="submit" class="btn btn-xl btn-full btn-lightblue text-left m-t-20">Guardar cambios <i class="icon-arrow-thin-right pull-right"></i></button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="modal" id="buscarGenerico">
    <div class="modal-overlay" data-dismiss="buscarGenerico"></div>

    <div class="modal-dialogo modal-dialogo-800">
        <div class="modal-header">
            <h2 data-icon="&#xe041;">Búsqueda</h2>
            <i class="icon-cross" data-dismiss="buscarGenerico"></i>
        </div>

        <div class="modal-contenido clearfix">
            @using (Ajax.BeginForm("_BuscarClub", "Temporada", null, new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = "resultadosBusqueda"@*, OnSuccess = "BuscarUsuario", OnFailure = "fBuscarUsuario"*@ }, new { @id = "RegistroForm", @class = "form-default clearfix" }))
            {
                <div class="col-md-12">
                    <label for="jugador-pagar" class="m-b-10">
                        <h3 class="inner-title m-t-0"> Buscár club</h3>
                    </label>
                </div>
                <div class="col-md-8">
                    <input type="text" name="Nombre" id="Nombre" placeholder="Nombre">
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-lightblue btn-full text-center"><i class="icon-search"></i> Buscar</button>
                </div>
            }

            <div class="col-md-12">
                <ul class="resultados-busqueda clearfix" id="resultadosBusqueda"></ul>

                <hr class="m-t-0 m-b-20">

            </div>

            <div class="col-md-4 col-md-offset-8">
                <button class="btn btn-full btn-red text-left m-t-20" onclick="javascript:seleccionarClub()" data-dismiss="buscarGenerico">Agregar<i class="icon-arrow-thin-right pull-right"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="exito">
    <div class="modal-overlay" data-dismiss="exito"></div>

    <div class="modal-dialogo modal-dialogo-600">
        <div class="modal-header">
            <h2 data-icon="&#xe04e;" id="tituloOperacion">¡Creación exitosa!</h2>
            <i class="icon-cross" data-dismiss="exito"></i>
        </div>

        <div class="modal-contenido clearfix">
            <div class="col-md-12 clearfix">
                <p id="msjOperacion">Has creado un nuevo temporada exitosamente. Recordá que puedes editarlo más tarde desde el panel de administración.</p>

                <div class="modal-opciones text-right">
                    <a href="@Url.Action("Index","Temporada")" class="btn btn-red m-t-0" data-dismiss="exito">Volver al listado</a>
                    <a href="@Url.Action("CrearTemporada","Temporada")" id="btnContinuar" class="btn btn-lightblue m-t-0" data-dismiss="exito">Crear otra temporada</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
        localStorage.setItem('opMenu', 'aLiTemporadaPuntos');
        $('#aLiCommunity').css('display', 'block');
        $('.submenu').addClass('open');
        
        $('.img-preview a.delete-img').click(function () {
            $(this).parent().slideUp(300).prev('input').val('');
            $(this).parent().next('img').slideUp(300);
            $(this).parent().parent().find('span').html(' ');
        });

        $('body').on('change', '.img-previewer', function () {
            if ($(this).val().length != 0) {
                src = window.URL.createObjectURL(this.files[0]);
                filename = $(this).val();
                $(this).next('.img-preview').find('img').attr('src', src).parent().slideDown(300);
                if (filename.substring(3, 11) == 'fakepath') {
                    filename = filename.substring(12);
                } $(this).parent().find('span').html(filename);

            }
            else {
                $(this).next().find('img').slideUp(300);

            }
        });

        $('#Accion, #Premio').on('keyup', function (event) {
            var len = $(this).val().length;
            if (len > 280) {
                $(this).val($(this).val().substring(0, 280));
                $(this).closest('div').find('#cantCaracter').text(280 - len);
            } else {
                $(this).closest('div').find('#cantCaracter').text(280 - len);
            }
        });

        function clickSeleccionClub(Codigo, Nombre) {
            Cod_Club = Codigo;
            txtNombreClub = Nombre;
        }

        var Cod_Club = 0;
        var txtNombreClub = "";
        function seleccionarClub() {
            $('#Codigo').val(Cod_Club);
            $('#txtNombreClub').html('<li>' + txtNombreClub + '<i class="icon-cross"></i></li>');
        }

        

        $(document).on('click', '#resultadosBusqueda li a', function () {
            $('#resultadosBusqueda li a').removeClass('marked');
            $(this).addClass('marked');
        });

        $(document).on('click', '.input-search ul li i', function () {
            $(this).parent().remove();
            $('#Codigo').val(0);
        });

        function fnSuccessProcesar(Data) {
            $('#msjOperacion').html(Data.Mensaje);
            if (Data.EsSatisfactorio) {
                $('#tituloOperacion').html('¡Creación exitosa!');
                setTimeout(function () {
                    window.location.href = '@Url.Action("Index", "Temporada")';
                }, 6000);
                $('#btnContinuar').css('display', 'inline-block');
                $('#btnPermanecer').css('display', 'none');
            } else {
                $('#tituloOperacion').html('¡Creación fállida!');
                $('#btnContinuar').css('display', 'none');
                $('#btnPermanecer').css('display', 'inline-block');
                console.log(Data);
            }
            $('#exito').css('display', 'block');
        }

        function fnFailProcesar(Data) {
            alert('Disculpe, temporalmente no es posible procesar su registro.');
            console.log(Data);
        }

    </script>

}

ProyectoAAPolo/AAPolo/Views/Temporada/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="col-md-12">
    <div class="panel panel-profile">
        <div class="panel-body">
            <h1 class="title-admin pull-left">Puntos Clubes</h1>
            <a href="@Url.Action("CrearRegistroPuntaje","Temporada")" class="btn btn-lightblue pull-right m-t-0"><i class="icon-plus"></i> Crear Nuevo</a>

            <div class="clearfix"></div>

            @Html.Action("_Listado", "Temporada")

            @*<ul class="pagination">
                    <li class="current"><a href="javascript:void(0);">1</a></li>
                    <li><a href="javascript:void(0);">2</a></li>
                    <li><a href="javascript:void(0);">3</a></li>
                    <li><a href="javascript:void(0);">4</a></li>
                    <li><a href="javascript:void(0);">5</a></li>
                    <li><a href="javascript:void(0);">6</a></li>
                    <li><a href="javascript:void(0);">7</a></li>
                    <li><a href="javascript:void(0);">8</a></li>
                    <li><a href="javascript:void(0);">9</a></li>
                    <li><a href="javascript:void(0);">10</a></li>
                </ul>*@
        </div>
    </div>
</div>

<div class="modal" id="exito">
    <div class="modal-overlay" data-dismiss="exito"></div>

    <div class="modal-dialogo modal-dialogo-600">
        <div class="modal-header">
            <h2 data-icon="&#xe04e;" id="tituloOperacion">¡Actualización exitosa!</h2>
            <i class="icon-cross" data-dismiss="exito"></i>
        </div>

        <div class="modal-contenido clearfix">
            <div class="col-md-12 clearfix">
                <p id="msjOperacion"></p>

                <div class="modal-opciones text-right">
                    <a href="#" id="btnContinuar" class="btn btn-lightblue m-t-0" data-dismiss="exito">Ok</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>
        localStorage.setItem('opMenu', 'aLiTemporadaPuntos');
        $('#aLiCommunity').css('display', 'block');
        $('.submenu').addClass('open');

        function cambiarEstatus(Codigo, Estado) {
            console.log(Codigo + ' - ' + Estado);
            var url = '@Url.Action("CambiarEstadoTemporada", "Temporada", new { Codigo = "_Codigo", EstadoTemporada = "_Estado" })'
                .replace('_Codigo', Codigo)
                .replace('_Estado', Estado)
                .replace(/amp;/g, '');

            console.log(url);
            $.post(url, function (Data) {

                $('#msjOperacion').html(Data.Mensaje);
                if (Data.EsSatisfactorio) {
                    $('#td_' + Codigo).attr('onclick', 'javascript:cambiarEstatus(' + Codigo + ',' + (Estado == 1 ? 0 : 1) + ')');
                    $('#tituloOperacion').html('¡Actualización exitosa!');
                } else {
                    $('#tituloOperacion').html('¡Actualización fállida!');
                    console.log(Data);
                }
                $('#exito').css('display', 'block');
            });
        }

    </script>

}

ProyectoAAPolo/AAPolo/Views/Temporada/_BuscarClub.cshtml
@model IEnumerable<AAPolo.Entities.Club>


@foreach (var item in Model)
{
    <li>
        <a href="javascript:void(0);" onclick="javascript:clickSeleccionClub(@item.Codigo,'@item.NombreClub')">
            <h3>@item.NombreClub</h3>
            @if (!String.IsNullOrEmpty(item.lDomicilio.FirstOrDefault().DireccionCompleta)) {
                <p>Ubicación: <strong>@item.lDomicilio.FirstOrDefault().DireccionCompleta</strong></p>
            }
        </a>
    </li>
}

ProyectoAAPolo/AAPolo/Views/Temporada/_Listado.cshtml
@model IEnumerable<AAPolo.Entities.PuntoXClub>

<table class="table-default table-admin paginarTabla">
    <thead>
        <tr>

            <th>Club Asociado</th>
            <th>Cantidad de Puntos</th>
            <th>Categoria de acción</th>
            <th>Acción</th>
            <th>Premio que canjeo</th>
            <th>Estado</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td data-label="Club Asociado"><a href="@Url.Action("EditarClub", "Club", new { Codigo = item.Codigo })">@item.NombreClub</a></td>
                <td data-label="Cantidad de Puntos">@item.Puntos</td>
                <td data-label="Categoria de acción">@item.CategoriaAccion.Nombre</td>
                <td data-label="Acción">@item.Accion</td>
                <td data-label="Fecha de carga">@item.Premio</td>
                <td id="td_@item.Cod_Canje" data-label="Estado" onclick="javascript:cambiarEstatus(@item.Cod_Canje, @(item.EsActivoCanje ? 0 : 1))">
                    <div class="toggle @(item.EsActivoCanje ? "toggle-active" : "") has-tooltip" title="Activo" data-on="Activo" data-off="Inactivo">
                        <div class="toggle-inner"></div>
                    </div>
                </td>
                <td data-label="Editar discplina" class="text-right"><a href="@Url.Action("EditarRegistroPuntaje", "Temporada", new { Codigo = item.Cod_Canje })" class="btn btn-lightblue btn-small">Editar Acción</a></td>
            </tr>
        }
    </tbody>
</table>

ProyectoAAPolo/AAPolo/Views/Temporada/_SelectCategiriaAccion.cshtml
@model IEnumerable<AAPolo.Entities.CategoriaAccion>

<option value="0" @(ViewBag.Codigo > 0 ? "" : "selected") disabled>Seleccione categoría</option>
@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Codigo == item.Codigo ? "selected" : "")>@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Temporada/_SelectTemporada.cshtml
@model IEnumerable<AAPolo.Entities.Temporada>

<option value="0" @(ViewBag.Codigo > 0 ? "" : "selected") disabled>Seleccione temporada</option>
@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Codigo == item.Codigo ? "selected" : "")>@item.Nombre</option>

}