ProyectoAAPolo/AAPolo/Controllers/CommunityController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class CommunityController : ClassHelper
    {
        // GET: Community
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Beneficio()
        {
            return View();
        }

        public ActionResult NuevoMiembro()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Jugador && !(DatosUsuario().Codigo > 0))
                return RedirectToAction("Index", "Home");

            Miembro miemb = new Miembro();
            try
            {
                var obj = (new PersonaSM().BuscaJugador(new Persona() { Codigo = DatosUsuario().Codigo }).FirstOrDefault());
                miemb = Cast<Miembro>(obj);
            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }

            miemb.EsMiembroJugador = true;
            return View(miemb);
        }

        [AllowAnonymous]
        public ActionResult NuevoMiembroAficionado(int ex=1)
        {
            bool ExigeTarjeta = ex== 1 ? true : false;
            
            ViewBag.ExigeTarjeta = ExigeTarjeta;

            return View(new Miembro() { EsMiembroJugador = false });
        }

        [AllowAnonymous]
        public ActionResult MiembroAficionado()
        {
            return View(new Miembro() { EsMiembroJugador = false });
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult _CuerpoForm(int Cod_TipoDocumento, string Documento, bool ExigeTarjeta) {
            Miembro miemb = new Miembro();
            try
            {
                ViewBag.ExigeTarjeta = ExigeTarjeta;
                miemb = new BeneficioSM().BuscarMiembro(Cod_TipoDocumento, Documento).FirstOrDefault();
                if (miemb!= null && !String.IsNullOrEmpty(miemb.DocumentoIdentidad))
                {
                    ViewBag.ExigeTarjeta = true;
                }
            }
            catch (Exception e)
            {

            }
            return PartialView(miemb);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult GuardarMiembroJugador(Miembro p)
        {
            ResultadoTransaccion result = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos valídos."
            };

            if (!String.IsNullOrEmpty(p.strFechaNacimiento) && p.Codigo == 0 && p.EsMiembroJugador == false)
            {
                try
                {
                    int Dia = Convert.ToInt32(p.strFechaNacimiento.Split('/')[0]),
                        Mes = Convert.ToInt32(p.strFechaNacimiento.Split('/')[1]),
                        Anio = Convert.ToInt32(p.strFechaNacimiento.Split('/')[2]);
                    p.FechaNacimiento = new DateTime(Anio, Mes, Dia);
                }
                catch (Exception)
                {
                    result.Mensaje = "Disculpe, debe ingresar una dirección de email válida.";
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }

            if (String.IsNullOrEmpty(p.Correo) || p.lContacto.Find(f => f.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email).Nombre != p.Correo)
            {
                result.Mensaje = "Disculpe, debe ingresar una dirección de email válida.";
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            if (!EsEmailValido(p.Correo))
            {
                result.Mensaje = "Disculpe, debe ingresar una dirección de email válida.";
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            try
            {
                result = new PersonaSM().GuardarMiembro(p);
            }
            catch (Exception e)
            {
                result.MensajeError = e.Message;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public PartialViewResult _Contacto(TipoContacto obj, Contacto contacto = null)
        {
            if (contacto == null)
            {
                contacto = new Contacto() { TipoContacto = obj };
            }
            else
            {
                contacto.TipoContacto = contacto.TipoContacto != null && !String.IsNullOrEmpty(contacto.TipoContacto.Nombre)? contacto.TipoContacto : obj;
                if (contacto.Nombre == null || contacto.Nombre.Equals(contacto.TipoContacto.Nombre) || String.IsNullOrEmpty(contacto.Nombre))
                {
                    //contacto.Nombre = "";
                    if (obj.Codigo == ConfiguracionAPP.TipoContacto_Email || contacto.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email)
                        contacto.Nombre = "noinformado@noinformado.com";
                    else
                        contacto.Nombre = "No informado";
                }
            }

            return PartialView(contacto);
        }

        [AllowAnonymous]
        public PartialViewResult _Domicilio(TipoDomicilio obj, Domicilio domicilio = null)
        {

            if (domicilio == null)
            {
                domicilio = new Domicilio()
                {
                    tipoDomicilio = obj
                };
            }
            else
            {
                domicilio.tipoDomicilio = obj;
            }

            return PartialView(domicilio);
        }

        [AllowAnonymous]
        public PartialViewResult _SelectGenero()
        {
            try
            {
                return PartialView(new PersonaSM().BuscarGenero());
            }
            catch (Exception e)
            {
                return PartialView(new List<Genero>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _SelectTipoDocumento()
        {
            try
            {
                return PartialView(new PersonaSM().BuscarTipoDocumento());
            }
            catch (Exception e)
            {
                return PartialView(new List<TipoDocumento>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _SelectPais(int Cod_Pais = 0)
        {
            try
            {
                ViewBag.Cod_Pais = Cod_Pais;
                return PartialView(new PersonaSM().BuscarPais());
            }
            catch (Exception e)
            {
                return PartialView(new List<Pais>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _SelectProvincia(int Codigo = 0, int Cod_Provincia = 0)
        {
            try
            {
                ViewBag.Cod_Provincia = Cod_Provincia;
                return PartialView(new PersonaSM().BuscarProvincia(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Provincia>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _SelectMunicipio(int Codigo = 0, int Cod_Municipio = 0)
        {
            try
            {
                ViewBag.Cod_Municipio = Cod_Municipio;
                return PartialView(new PersonaSM().BuscarMunicipio(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Municipio>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _ListadoBeneficioDestacado() {
            try
            {
                return PartialView(new BeneficioSM().BuscarBeneficioDestacadoActivo(0, "", 0, 0, true));
            }
            catch (Exception e)
            {
                return PartialView(new List<Beneficio>());
            }    
        }

        [AllowAnonymous]
        public PartialViewResult _ListadoBeneficioDestacadoLanding()
        {
            try
            {
                return PartialView(new BeneficioSM().BuscarBeneficioDestacadoActivo(0, "", 0, 0, true));
            }
            catch (Exception e)
            {
                return PartialView(new List<Beneficio>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _ListadoBeneficioActivo(string Contenido = "", int CodTipoBeneficiario = 1, string lstCodCategoriaBeneficio = "")
        {
            try
            {
                List<Beneficio> lstBeneficio = new BeneficioSM().BuscarBeneficioActivo(0, Contenido, 0, CodTipoBeneficiario, true);
                if (!String.IsNullOrEmpty(lstCodCategoriaBeneficio)) {
                    List<int> lstCod = lstCodCategoriaBeneficio.Split(',').Select(Int32.Parse).ToList();

                    lstBeneficio = lstBeneficio.Where(x => lstCod.Any(a => a == x.CategoriaBeneficio.Codigo)).ToList();

                }

                return PartialView(lstBeneficio);
            }
            catch (Exception e)
            {
                return PartialView(new List<Beneficio>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _ListaCategoriaBeneficio() {
            try
            {
                return PartialView(new BeneficioSM().BuscarCategoriaBeneficio());
            }
            catch (Exception e)
            {
                return PartialView(new List<CategoriaBeneficio>());
            }
        }

        [AllowAnonymous]
        public ActionResult _ListaTipoBeneficiario()
        {
            try
            {
                return PartialView(new BeneficioSM().BuscarTipoBeneficiario());
            }
            catch (Exception e)

ProyectoAAPolo/AAPolo/Views/Community/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<link href="@Url.Content("~/Content/css/jquery.fullpage.css")" rel="stylesheet" />

<div id="fullpage">

    <section class="section section-slider-main" id="section1">
        <div class="section-slider">

            <div class="section-inicio">
                <div class="section-slider-holder">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9">
                                <div class="">
                                    <h1>Polo Community</h1>
                                    <h4>El programa de beneficios exclusivo que conecta a la comunidad del polo.</h4>
                                    @*<a href="#registro" class="btn btn-outline m-t-10 m-b-10">Quiero asociarme</a>*@
                                    <a href="#registro" class="btn m-t-10 m-b-10">¡Asociate ahora!</a>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <img class="pull-right" src="@Url.Content("~/Content/img/community-tar.png")" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section-como">
                <div class="section-slider-holder">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="text-center">
                                    <h1>¡Ser parte es muy fácil! Seguí estos 4 pasos</h1>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3 col-xs-6">
                                    <div class="tarjeta-community-pasos">
                                        <div class="community-pasos" data-icon="P"></div>
                                        <h3>Escribinos y obtené tu tarjeta <a href="mailto:info@aapolo.com" target="_blank" tabindex="-1">info@aapolo.com</a></h3>
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-6">
                                    <div class="tarjeta-community-pasos">
                                        <div class="community-pasos" data-icon="("></div>
                                        <h3>Cargá tus datos y tu tarjeta en el formulario</h3>
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-6">
                                    <div class="tarjeta-community-pasos">
                                        <div class="community-pasos" data-icon="S"></div>

                                        <h3>Aceptá los términos y condiciones</h3>
                                    </div>
                                </div>
                                <div class="col-md-3 col-xs-6">
                                    <div class="tarjeta-community-pasos">
                                        <div class="community-pasos" data-icon=""></div>
                                        <h3>¡Disfrutá de los beneficios!</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="registro-footer">
            <div class="container-fluid">
                <div class="col-md-12">
                    <h4 class="pull-left">Conoce los beneficios desde donde estés.</h4>
                    <div class="pull-right m-t-20">
                        <a href="https://play.google.com/store/apps/details?id=com.amedia.aapolo"><img src="@Url.Content("~/Content/img/google-app.png")" alt="Google Play" style="height: 46px"></a>
                        <a href="https://apps.apple.com/gb/app/aapolo/id1435131234"><img src="@Url.Content("~/Content/img/ios-app.png")" alt="App Store" style="height: 46px"></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section fp-auto-height section-beneficios" id="section2">
        <div class="container-fluid">

            @Html.Action("_ListadoBeneficioDestacadoLanding", "Community")
        </div>
    </section>

    <section class="section section-registro" id="section3">

        <div class="container-fluid">
            <div class="col-md-12">
                <div class="text-center">
                    <h1>¡Viví la experiencia Polo Community!</h1>
                    @*<h3>Registrate y forma parte de la casa del mejor polo del mundo.</h3>*@
                    <h3>Registrate y formá parte del mejor polo del mundo.</h3>
                </div>
            </div>
            <div class="col-md-12 items-center">
                <div class="col-md-5">
                    <div class="tarjeta-community-in text-center">
                        <img src="@Url.Content("~/Content/img/community-tar1.png")" alt="">
                        <h3>Polo Players</h3>
                        <p>Si ya sos jugador validá tus datos y disfruta de los beneficios.</p>

                        @if (Request.IsAuthenticated)
                        {
                            <a href="@Url.Action("NuevoMiembro", "Community")" class="btn text-center">Accede a los beneficios</a>
                        }
                        else
                        {
                            <a href="javascript:void(0);" class="btn text-center" data-modal="iniciarSesion" onclick="javascript:localStorage.setItem('redirigir','@Url.Action("NuevoMiembro","Community")')">Accede a los beneficios</a>
                        }
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="tarjeta-community-in text-center">
                        <img src="@Url.Content("~/Content/img/community-tar2.png")" alt="">
                        <h3>Polo Members</h3>
                        @*<p>Si sos fanático del deporte completá tus datos y disfruta de los beneficios</p>*@
                        <p>Si sos fanático del deporte registrate y disfruta de los beneficios.</p>
                        <a href="@Url.Action("NuevoMiembroAficionado", "Community", new { ex = 0})" class="btn  text-center">Pedir mi tarjeta</a>
                        @*<a href="@Url.Action("NuevoMiembroAficionado", "Community")" class="btn  text-center">Accede al formulario</a>*@
                    </div>
                </div>
            </div>
        </div>
       
    </section>

</div>



<div class="modal" id="terminosCondicionesBeneficios" style="display: none;">
    <div class="modal-overlay" data-dismiss="terminosCondicionesBeneficios"></div>

    <div class="modal-dialogo modal-dialogo-600">
        <div class="modal-header">
            <h2><i class="icon-information"></i> Términos y condiciones de beneficio</h2>
            <i class="icon-cross" data-dismiss="terminosCondicionesBeneficios"></i>
        </div>

        <div class="modal-contenido clearfix">
            <div class="col-md-12 clearfix">
                <p id="txtTerminoYCondicion">

                </p>
            </div>
        </div>
    </div>
</div>

@section scripts{


    <script src="@Url.Content("~/Scripts/scrolloverflow.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.fullpage.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.fullpage.extensions.min.js")"></script>

    <script>

        localStorage.setItem('opMenu', 'liPoloCommunity');

        setTimeout(function () {
            $('#liPoloCommunityLanding').addClass('current');
        },500);

        $('#fullpage').fullpage({
            'anchors': ['inicio', 'beneficios', 'registro'],
            'navigation': false,
            'navigationPosition': 'right',
            'navigationTooltips': ['Inicio', '¿Cómo formar parte?', '¿Qué es?', 'Registro'],
            'scrollBar': true,
            'paddingTop': '50px',
            'responsiveWidth': 1280,
            'responsiveHeight': 768,
            'scrolloverflow': true,

        });



        $('.section-slider').slick({
            slidesToShow: 1,
            dots: false,
            nav: true,
            arrows: false,
            autoplay: true,
            autoplaySpeed: 1500,
            speed: 500,
            responsive: [
                {
                    breakpoint: 480,
                    settings: {
                        arrows: false,
                    }
                }
            ]
        });

        $('.carousel-cards-destacado, .carousel-cards').slick({
            dots: true,
            infinite: false,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 1,
            arrows: false,
            autoplay: false,
            autoplaySpeed: 2000,
            responsive: [
                {
                    breakpoint: 1260,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 992,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 800,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        dots: false,
                        arrows: true,
                    }
                }
                // You can unslick at a given breakpoint now by adding:
                // settings: "unslick"
                // instead of a settings object
            ]
        });

        $(document).ready(function (e) {
            fixHeight('.tarjeta-community-pasos');
            if ($(window).width() > 768) {
                fixHeight('.beneficio-destacado');
                fixHeight('.beneficio');
            }
        });

    </script>


}

ProyectoAAPolo/AAPolo/Views/Community/_Contacto.cshtml
@model AAPolo.Entities.Contacto
@using AAPolo.Entities;

@using (Html.BeginCollectionItem("lContacto"))
{
    @Html.HiddenFor(model => model.TipoContacto.Codigo)
    @Html.HiddenFor(model => model.Codigo)
    <label for="@Html.IdFor(model => model.Nombre)">@Model.TipoContacto.Nombre</label>
    @Html.TextBoxFor(model => model.Nombre, new { @class = (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email ? "CampoRequerido ValidarMail" : "") + " " + (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Celular ? " TelefonoUsuario RequerimientoMinimo CampoRequerido" : ""), @data_min = "6", @data_txtrequerimientominimo = "Disculpe, debe tener al menos 6 caracteres.", @data_textcamporequerid = (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email ? "Por favor, ingrese mail" : "Por favor, ingrese teléfono") })
}

ProyectoAAPolo/AAPolo/Views/Community/_CuerpoForm.cshtml
@model AAPolo.Entities.Miembro
@using AAPolo.Entities;

<div class="col-md-12">
    <h3>Información personal</h3>
</div>

<div class="col-md-4">
    <label for="nombre">Nombre</label>
    @Html.TextBoxFor(model => model.Nombre, new { @class = "CampoRequerido", @data_textCampoRequerid = "Por favor, ingrese nombre" })
</div>

<div class="col-md-4">
    <label for="apellido">Apellido</label>
    @Html.TextBoxFor(model => model.Apellido, new { @class = "CampoRequerido", @data_textCampoRequerid = "Por favor, ingrese apellido" })
</div>

<div class="col-md-4">
    <label for="genero">Género</label>
    <select name="@Html.NameFor(model => model.Genero.Codigo)" id="@Html.IdFor(model => model.Genero.Codigo)" class="select2-basic CampoRequerido" data-textCampoRequerid="Por favor, seleccione genero">
        @Html.Action("_SelectGenero")
    </select>
</div>

<div class="col-md-4">
    <label for="strFechaNacimiento">Fecha de nacimiento</label>
    @Html.TextBoxFor(model => model.strFechaNacimiento, new { @class = "datepicker CampoRequerido", @data_textCampoRequerid = "Por favor, ingrese fecha de nacimiento" })
</div>

<div class="col-md-4">
    <label for="Correo">Email <i class="icon-question has-tooltip" title="Debe coincidir con el campo confirmación de email"></i></label>
    @Html.TextBoxFor(model => model.Correo, new { @class = "CampoRequerido ValidarMail", @value = (Model == null || String.IsNullOrEmpty(Model.Correo) ? "noinformado@noinformado.com" : Model.Correo), @data_textcamporequerid = "Por favor, ingrese una dirección de email válida." })
</div>

<div class="col-md-4">
    @Html.Action("_Contacto", new Contacto() { Nombre = (Model == null || String.IsNullOrEmpty(Model.Correo)? "" : Model.Correo), TipoContacto = new TipoContacto() { Codigo = ConfiguracionAPP.TipoContacto_Email, Nombre = "Confirmar email" } })
</div>

<div class="col-md-4">
    @Html.Action("_Contacto", new Contacto() { Nombre = (Model == null || String.IsNullOrEmpty(Model.TelefonoMiembro) ? "" : Model.TelefonoMiembro), TipoContacto = new TipoContacto() { Codigo = ConfiguracionAPP.TipoContacto_Celular, Nombre = "Celular" } })
</div>

@if (ViewBag.ExigeTarjeta == true)
{
    <div class="col-md-4">
        <label for="NumeroTarjeta">Número de tarjeta <i class="icon-question has-tooltip" title="Si no tenés tarjeta aún pedila  a info@aapolo.com"></i></label>
        @Html.TextBoxFor(model => model.NumeroTarjeta, new { @class = "CampoRequerido has-tooltip", @title = "Si no tenés tarjeta aún pedila  a info@aapolo.com", @placeholder = "EJ xxxxxxxxxxxxxxxxxxxxxx", @data_textCampoRequerid = "Por favor, ingrese número de tarjeta." })
    </div>
}

<div class="col-md-4 m-t-40">
    <input type="checkbox" name="checkCondicionMiembro" id="checkCondicionMiembro" data-valor="0" readonly>
    <label for="admin">
        <a href="javascript:void(0);" data-modal="terminos-condiciones-miembro">Términos y Condiciones</a>
    </label>
</div>

<div class="col-md-4 col-md-offset-8">
    <button type="submit" id="CargarFormMiembro" style="visibility:hidden">Guardar cambios </button>
    <button type="button" class="btn btn-xl btn-full btn-lightblue text-left m-t-20" onclick="javascript:GuardarJugador(this)" disabled="disabled" id="btnFormMiembro">Enviar <i class="icon-arrow-thin-right pull-right"></i></button>
</div>

<script>

    $(document).ready(function () {
        $('.datepicker').pickadate({
            firstDay: 0,
            container: 'body',
            format: 'dd/mm/yyyy',
            max: true,
            minDate: '1918',
            selectYears: true,
            selectMonths: true,
            selectYears: 100
        });

        if ($('#Correo').val() == '')
            $('.ValidarMail').val('');

        var tlf = '@(Model == null || String.IsNullOrEmpty(Model.TelefonoMiembro) ? "": Model.TelefonoMiembro)';

        console.log('tlf: "' + tlf + '"');
        if (tlf == '') {
            $('.TelefonoUsuario').val('');
        }

    });

</script>

ProyectoAAPolo/AAPolo/Views/Community/_ListaCategoriaBeneficio.cshtml
@model IEnumerable<AAPolo.Entities.CategoriaBeneficio>

@foreach (var item in Model)
{
    <li>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="" onclick="javascript:CargarCategoria(@item.Codigo)">
                <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                <span class="cat-name">@item.Nombre</span>
            </label>
        </div>
    </li>
}

ProyectoAAPolo/AAPolo/Views/Community/_ListadoBeneficioDestacadoLanding.cshtml
@model IEnumerable<AAPolo.Entities.Beneficio>
@using AAPolo.Entities;

<div class="wrapper">
    <div class="col-md-12">

        <div class="title-container m-b-20">
            <h1 class="page-title m-b-0 m-t-0" style="color: #fff">Conocé los beneficios que tenemos para vos</h1>
            @if (Model != null && Model.Count() > 0) {
                <a href="@Url.Action("Beneficio", "Community")" class="btn btn-outline btn-small m-t-10 pull-right">Ver catálogo</a>
            }
        </div>
        <div class="clearfix"></div>

    </div>
    <div class="col-md-12">
        <div class="row carousel-cards-destacado">

            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-sm-6 col-xs-12">
                    <div class="noticia noticia-sm clearfix beneficio">
                        <div class="noticia-img" style="background-image: url('@Url.Content(item.UrlImagen)')"></div>
                        <a href="javascript:void(0)" class="noticia-categoria">@item.CategoriaBeneficio.Nombre</a>
                        <h3>@item.Nombre</h3>
                        <p>@item.Descripcion</p>
                        <div class="beneficio-footer">
                            <ul class="beneficio-links">
                                @if (!String.IsNullOrEmpty(item.UrlMarca))
                                {
                                    <li><a href="@("https://"+(item.UrlMarca.Replace("http://","").Replace("https://", "")))" target="_blank"><i class="icon-web"></i> @item.UrlMarca.Replace("http://", "").Replace("https://", "")</a></li>
                                }

                                @if (!String.IsNullOrEmpty(item.Condicion))
                                {
                                    <li><a href="javascript: void(0)" data-modal="terminosCondicionesBeneficios" onclick="$('#txtTerminoYCondicion').html('@Html.Raw(item.Condicion.Replace("\r", "<br>").Replace("\n", "<br>"))')"><i class="icon-information"></i> Requisitos</a></li>
                                }
                            </ul>
                            <ul class="descuentos">
                                @if (item.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloTodos || item.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloPlayers)
                                {
                                    <li class="descuento-players">
                                        <span>@item.lstPrecioXBeneficios.Find(f => f.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloPlayers).Precio</span>
                                        <span>Polo Players</span>
                                    </li>
                                }
                                @if (item.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloTodos || item.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloMembers)
                                {
                                    <li class="descuento-members">
                                        <span>@item.lstPrecioXBeneficios.Find(f => f.TipoBeneficiario.Codigo == ConfiguracionAPP.Cod_TipoBeneficiario_PoloMembers).Precio</span>
                                        <span>Polo Members</span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>

            }


        </div>
    </div>
</div>

ProyectoAAPolo/AAPolo/Views/Community/_SelectGenero.cshtml
@model IEnumerable<AAPolo.Entities.Genero>


<option value="0" selected disabled>Seleccione genero</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo">@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Community/_SelectPais.cshtml
@model IEnumerable<AAPolo.Entities.Pais>


<option value="0" @(ViewBag.Cod_Pais == 0 ? "selected":"") disabled>Seleccione país</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Cod_Pais == item.Codigo ? "selected":"")>@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Community/_SelectTipoDocumento.cshtml
@model IEnumerable<AAPolo.Entities.TipoDocumento>


<option value="0" selected disabled>Seleccione tipo de documento</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo">@item.Nombre</option>

}