ProyectoAAPolo/AAPolo/Controllers/JugadorController.cs
using AAPolo.Aplication;
using AAPolo.Controllers.Helper;
using AAPolo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAPolo.Controllers
{
    [Authorize]
    public class JugadorController : ClassHelper
    {
        // GET: Jugador
        public ActionResult Index()
        {
            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");
            return View();
        }

        public PartialViewResult Listado(int Cod_Persona = 0, string Cadena = "", int Cod_TipoJugador = 0, int Cod_Club = 0, int Nro_Handicap = -1)
        {
            //List<Persona> lPersona = new PersonaSM().BuscaJugadorResumen(Cod_Persona, Cadena, Cod_TipoJugador, Cod_Club, Nro_Handicap, 0);
            List<Persona> lPersona = new PersonaSM().BuscaJugadorDetalleResumen(Cod_Persona, Cadena, Cod_TipoJugador, Cod_Club, Nro_Handicap, 0);
            return PartialView(lPersona);
        }

        public ActionResult CrearJugador()
        {

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            return View();
        }

        public ActionResult EditarJugador(int Codigo = 0)
        {
            if (Codigo == 0)
                return RedirectToAction("Index");

            if (DatosUsuario().Rol.Codigo != ConfiguracionAPP.Rol_Administrador)
                return RedirectToAction("Index", "Home");

            Persona p = new Persona() { Codigo = Codigo };
            try
            {
                p = new PersonaSM().BuscaJugador(p).FirstOrDefault();

            }
            catch (Exception e)
            {
                ViewBag.MensajeError = e.Message;
                return RedirectToAction("Index");
            }
            if (p == null || p.Codigo == 0)
                return RedirectToAction("Index");

            if (String.IsNullOrEmpty(p.DocumentoIdentidad) || p.DocumentoIdentidad.Equals("1"))
                p.DocumentoIdentidad = "No Informado";

            return View(p);
        }
        
        public JsonResult _CrearJugador(Persona obj, List<int> _lClubUsuarioSecundario = null, int Cod_Handicap = 0, int NroHandicap = 0, int NroHandicapSecundario = 0)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                if (!String.IsNullOrEmpty(obj.strFechaNacimiento))
                {
                    int Dia = Convert.ToInt32(obj.strFechaNacimiento.Split('-')[0]),
                        Mes = Convert.ToInt32(obj.strFechaNacimiento.Split('-')[1]),
                        Anio = Convert.ToInt32(obj.strFechaNacimiento.Split('-')[2]);
                    obj.FechaNacimiento = new DateTime(Anio, Mes, Dia);
                }

                if (!obj.EsMember)
                {
                    obj.HandicapPersona = new HandicapPersona()
                    {
                        Codigo = Cod_Handicap,
                        NroHandicap = NroHandicap
                    };

                    obj.HandicapPersonaSecundario = new HandicapPersona()
                    {
                        NroHandicap = NroHandicapSecundario
                    };

                    if (_lClubUsuarioSecundario != null && _lClubUsuarioSecundario.Count() > 0)
                    {
                        obj.lClubUsuarioSecundario = (from value in _lClubUsuarioSecundario
                                                      where value > 0
                                                      select new ClubUsuario() { Codigo = value }).ToList();
                    }
                }

                if (obj.Foto != null)
                {
                    obj.UrlFoto = GuardarImagen(obj.Foto);
                }
                else
                {
                    obj.UrlFoto = "";
                }

                if (obj.EsReferee && obj.TipoReferee != null && obj.TipoReferee.Codigo < 1)
                {
                    resul.Mensaje = "Por favor, seleccione el tipo de referees.";
                }
                else if ((obj.Codigo == 0 && !obj.DocumentoIdentidad.ToLower().Equals("no informado".ToLower())) || obj.Codigo > 0)
                {
                    resul = new PersonaSM().GuardarJugador(obj, DatosUsuario().Codigo);
                }
                else
                {
                    resul.Mensaje = "Por favor, ingrese un documento válido.";
                }
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstadoJugador(int Codigo, int EstadoJugador)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new PersonaSM().CambiarEstadoJugador(Codigo, EstadoJugador);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstadoDestacadoJugador(int Codigo, int EstadoDestacadoJugador)
        {
            ResultadoTransaccion resul = new ResultadoTransaccion()
            {
                EsSatisfactorio = false,
                Mensaje = "Disculpe, debe ingresar datos válidos"
            };

            try
            {
                resul = new PersonaSM().CambiarEstadoDestacadoJugador(Codigo, EstadoDestacadoJugador);
            }
            catch (Exception e)
            {
                resul.MensajeError = e.Message;
            }

            return Json(resul, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _SelectGenero()
        {
            try
            {
                return PartialView(new PersonaSM().BuscarGenero());
            }
            catch (Exception e)
            {
                return PartialView(new List<Genero>());
            }
        }

        public PartialViewResult _SelectTipoDocumento()
        {
            try
            {
                return PartialView(new PersonaSM().BuscarTipoDocumento());
            }
            catch (Exception e)
            {
                return PartialView(new List<TipoDocumento>());
            }
        }

        public PartialViewResult _SelectPais(int Cod_Pais = 0)
        {
            try
            {
                ViewBag.Cod_Pais = Cod_Pais;
                return PartialView(new PersonaSM().BuscarPais());
            }
            catch (Exception e)
            {
                return PartialView(new List<Pais>());
            }
        }

        public PartialViewResult _SelectProvincia(int Codigo = 0, int Cod_Provincia = 0)
        {
            try
            {
                ViewBag.Cod_Provincia = Cod_Provincia;
                return PartialView(new PersonaSM().BuscarProvincia(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Provincia>());
            }
        }

        public PartialViewResult _SelectMunicipio(int Codigo = 0, int Cod_Municipio = 0)
        {
            try
            {
                ViewBag.Cod_Municipio = Cod_Municipio;
                return PartialView(new PersonaSM().BuscarMunicipio(Codigo));
            }
            catch (Exception e)
            {
                return PartialView(new List<Municipio>());
            }
        }

        [AllowAnonymous]
        public PartialViewResult _SelectTipoJugador(string FechaNacimiento = "")
        {
            int Edad = 0;
            if (!FechaNacimiento.Equals(""))
            {
                int Dia = Convert.ToInt32(FechaNacimiento.Split('-')[0]),
                    Mes = Convert.ToInt32(FechaNacimiento.Split('-')[1]),
                    Anio = Convert.ToInt32(FechaNacimiento.Split('-')[2]);

                DateTime dtFechaNacimiento = new DateTime(Anio, Mes, Dia);

                Edad = DateTime.Today.Year - dtFechaNacimiento.Year;
            }

            try
            {
                List<TipoJugador> lJugador = new PersonaSM().BuscarTipoJugador();
                if (Edad > 0)
                    lJugador = lJugador.Where(x => Edad >= x.EdadDesde && Edad <= x.EdadHasta).ToList();

                return PartialView(lJugador);
            }
            catch (Exception e)
            {
                return PartialView(new List<TipoJugador>());
            }
        }

        public PartialViewResult _Contacto(TipoContacto obj, Contacto contacto = null, int CodContactoUsuario = 0)
        {
            if (contacto == null)
            {
                contacto = new Contacto() { TipoContacto = obj };
            }
            else
            {
                contacto.TipoContacto = obj;
                if ((contacto.Nombre.Equals(contacto.TipoContacto.Nombre) || String.IsNullOrEmpty(contacto.Nombre)) && CodContactoUsuario > 0)
                {
                    //contacto.Nombre = "";
                    if (obj.Codigo == ConfiguracionAPP.TipoContacto_Email)
                        contacto.Nombre = "noinformado@noinformado.com";
                    else
                        contacto.Nombre = "No informado";
                }
                else if (contacto.Nombre.Equals(contacto.TipoContacto.Nombre) && CodContactoUsuario == 0)
                {
                    contacto.Nombre = "";

                }
            }

ProyectoAAPolo/AAPolo/Views/Jugador/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="col-md-12">

    <div class="panel panel-profile">
        <div class="panel-body">
            <h1 class="title-admin pull-left">Jugadores</h1>
            <a href="@Url.Action("CrearJugador")" class="btn btn-lightblue pull-right m-t-0"><i class="icon-plus"></i> Crear jugador</a>
            <a href="@Url.Action("GetReporteJugadores","Reporte")" target="_blank" download class="btn btn-lightblue pull-right m-t-0 m-r-10"><i class="icon-plus"></i> Descargar excel</a>
            
            <div class="clearfix"></div>

            @using (Ajax.BeginForm("Listado", "Jugador", null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "BuscarJugador", OnFailure = "fBuscarJugador" }, new { @id = "RegistroForm", @class = "form-default row" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()

                <div class="col-md-3">
                    <input id="Cadena" name="Cadena" type="text" placeholder="Buscar jugadores por nombre o número de documento" class="ng-pristine ng-valid ng-empty ng-touched" style="" autocomplete="off">
                </div>

                <div class="col-md-3">
                    <select id="Cod_TipoJugador" name="Cod_TipoJugador" onchange="javascript: $('#btnFiltro').click()" class="select2-basic">
                        @Html.Action("_SelectTipoJugador", "Jugador")
                    </select>
                </div>

                <div class="col-md-2">
                    <select id="Cod_Club" name="Cod_Club" onchange="javascript: $('#btnFiltro').click()" class="select2-basic">
                        <option value="0" selected>Seleccione club</option>
                        @Html.Action("_SelectClub", "Jugador")
                    </select>

                </div>

                <div class="col-md-2">
                    @*<input id="Nro_Handicap" name="Nro_Handicap" type="number" placeholder="Buscar jugadores por número de handicap" class="ng-pristine ng-untouched ng-valid ng-empty">*@
                    <select class="select2-basic" id="Nro_Handicap" name="Nro_Handicap" onchange="javascript: $('#btnFiltro').click()">
                        <option value="-1">Handicap general</option>
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>

                <div class="col-md-2">
                    <button type="submit" class="btn btn-lightblue btn-full" id="btnFiltro"><i class="icon-search"></i> Buscar</button>
                </div>

            }

            <div class="listadoTabla">
                @Html.Action("Listado")
            </div>

        </div>
    </div>
</div>

<div class="modal" id="exito">
    <div class="modal-overlay" data-dismiss="exito"></div>

    <div class="modal-dialogo modal-dialogo-600">
        <div class="modal-header">
            <h2 data-icon="&#xe04e;" id="tituloOperacion">¡Actualización exitosa!</h2>
            <i class="icon-cross" data-dismiss="exito"></i>
        </div>

        <div class="modal-contenido clearfix">
            <div class="col-md-12 clearfix">
                <p id="msjOperacion"></p>

                <div class="modal-opciones text-right">
                    <a href="#" id="btnContinuar" class="btn btn-lightblue m-t-0" data-dismiss="exito">Ok</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>

        localStorage.setItem('opMenu', 'aLiJugador');

        @*_Listado();
        function _Listado() {
            var urlListado = '@Url.Action("Listado")';
            $.post(urlListado, function (Data) {
                BuscarJugador(Data);
            });
        }*@

        function BuscarJugador(Data) {
            if (Data != null) {
                $('.listadoTabla').html(Data);
                PaginacionDeTablas('.paginarTabla', 20);
            }

        }

        function fBuscarJugador(Data) {
            alert('Disculpe, no es posible realizar la busqueda.');
            console.log(Data);
        }

        function cambiarEstatus(Codigo, Estado) {
            console.log(Codigo + ' - ' + Estado);
            var url = '@Url.Action("CambiarEstadoJugador","Jugador", new { Codigo = "_Codigo", EstadoJugador = "_Estado" })'
                .replace('_Codigo', Codigo)
                .replace('_Estado', Estado)
                .replace(/amp;/g, '');

            $.post(url, function (Data) {
                
                $('#msjOperacion').html(Data.Mensaje);
                if (Data.EsSatisfactorio) {
                    $('#td_' + Codigo).attr('onclick', 'javascript:cambiarEstatus(' + Codigo + ',' + (Estado == 1 ? 0 : 1) + ')');
                    $('#tituloOperacion').html('¡Actualización exitosa!');
                    if (Estado == 0) {
                        $('#td_' + Codigo + ' .toggle').removeClass('toggle-active');
                    } else {
                        $('#td_' + Codigo + ' .toggle').addClass('toggle-active');
                    }
                } else {
                    $('#td_' + Codigo + ' .toggle').toggleClass('toggle-active');
                    $('#tituloOperacion').html('¡Actualización fállida!');
                    console.log(Data);
                }
                $('#exito').css('display', 'block');
            });
        }

        function cambiarEstatusDestacado(Codigo, Estado) {
            console.log(Codigo + ' - ' + Estado);
            var url = '@Url.Action("CambiarEstadoDestacadoJugador","Jugador", new { Codigo = "_Codigo", EstadoDestacadoJugador = "_Estado" })'
                .replace('_Codigo', Codigo)
                .replace('_Estado', Estado)
                .replace(/amp;/g, '');

            $.post(url, function (Data) {
                
                $('#msjOperacion').html(Data.Mensaje);
                if (Data.EsSatisfactorio) {
                    $('#td_des_' + Codigo).attr('onclick', 'javascript:cambiarEstatusDestacado(' + Codigo + ',' + (Estado == 1 ? 0 : 1) + ')');
                    $('#tituloOperacion').html('¡Actualización exitosa!');
                } else {
                    $('#td_des_' + Codigo + ' .toggle').toggleClass('toggle-active');
                    $('#tituloOperacion').html('¡Actualización fállida!');
                    console.log(Data);
                }
                $('#exito').css('display', 'block');
            });
        }

    </script>


}

ProyectoAAPolo/AAPolo/Views/Jugador/Listado.cshtml
@model IEnumerable<AAPolo.Entities.Persona>

<table class="table-default table-admin paginarTabla">
    <thead>
        <tr>
            <th>Nombre y apellido</th>
            <th>Tipo jugador</th>
            <th>Handicap</th>
            <th>Categoria de handicap</th>
            <th>Tipo handicap</th>
            <th>Club</th>
            <th>Nacionalidad</th>
            <th>Destacado</th>
            <th>Estado</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td data-label="Nombre y apellido">
                        <a href="@Url.Action("EditarJugador", new { Codigo = item.Codigo })">@item.NombreCompleto</a>
                    </td>
                    <td data-label="Tipo de jugador">@item.TipoJugador.Nombre</td>
                    <td data-label="Handicap">
                        @if (item.EsMember == false || item.HandicapPersona.NroHandicap > -1)
                        {
                            @item.HandicapPersona.NroHandicap
                        }
                        else
                        {
                            @Html.Raw("-")
                        }
                    </td>
                    <td data-label="Categoria de handicap">@item.HandicapPersona.Categoria.Nombre</td>
                    <td data-label="Tipo de handicap">@item.HandicapPersona.Nombre</td>
                    <td data-label="Club"><a href="@Url.Action("EditarClub", "Club", new { Codigo = item.clubUsuarioPrincipal.Codigo })">@item.clubUsuarioPrincipal.NombreClub</a></td>
                    <td data-label="Nacionalidad">@item.Pais.Nombre</td>
                    <td data-label="Destacado" id="td_des_@item.Codigo" onclick="javascript:cambiarEstatusDestacado(@item.Codigo, @(item.EsDestacado ? 0 : 1))">
                        <div class="toggle @(item.EsDestacado ? "toggle-active" : "") has-tooltip" title="Activo" data-on="Activo" data-off="Inactivo">
                            <div class="toggle-inner"></div>
                        </div>
                    </td>
                    @if (!item.EsMember)
                    {
                        <td data-label="Estado" id="td_@item.Codigo" onclick="javascript:cambiarEstatus(@item.Codigo, @(item.EsActivo ? 0 : 1))">
                            <div class="toggle @(item.EsActivo ? "toggle-active" : "") has-tooltip" title="Activo" data-on="Activo" data-off="Inactivo">
                                <div class="toggle-inner"></div>
                            </div>
                        </td>
                    }
                    else
                    {
                        <td data-label="Estado" id="td_@item.Codigo">
                            <div class="toggle @(item.EsActivo ? "toggle-active" : "") has-tooltip disabled" title="Activo" data-on="Activo" data-off="Inactivo">
                                <div class="toggle-inner"></div>
                            </div>
                        </td>
                    }
                    <td data-label="Editar perfil" class="text-right">
                        <a href="@Url.Action("EditarJugador", new { Codigo = item.Codigo })" class="btn btn-lightblue btn-small">Editar perfil</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td data-label="Nombre y apellido">
                    <span>No se encontraron resultados</span>
                </td>
                <td data-label="Tipo de jugador"> </td>
                <td data-label="Handicap"> </td>
                <td data-label="Categoria de handicap"> </td>
                <td data-label="Tipo de handicap"> </td>
                <td data-label="Club"> </td>
                <td data-label="Nacionalidad"> </td>
                <td data-label="Estado"></td>
                <td data-label="Editar perfil" class="text-right"></td>
            </tr>
        }
    </tbody>
</table>

ProyectoAAPolo/AAPolo/Views/Jugador/_BuscarTipoReferee.cshtml
@model IEnumerable<AAPolo.Entities.TipoReferee>

<option value="0" selected>Seleccione categoría de referre</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(item.Codigo == ViewBag.Cod_TipoReferee? "selected": "")>@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_Contacto.cshtml
@model AAPolo.Entities.Contacto
@using AAPolo.Entities;

@using (Html.BeginCollectionItem("lContacto"))
{
    @Html.HiddenFor(model => model.TipoContacto.Codigo)
    @Html.HiddenFor(model => model.Codigo)
    <label for="@Html.IdFor(model => model.Nombre)">@Model.TipoContacto.Nombre</label>
    @Html.TextBoxFor(model => model.Nombre, new { @class = (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email ? "CampoRequerido ValidarMail" : "") + " " + (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Celular ? " TelefonoUsuario RequerimientoMinimo CampoRequerido" : ""), @data_min = "6", @data_txtrequerimientominimo = "Disculpe, debe tener al menos 6 caracteres.", @data_textcamporequerid = (Model.TipoContacto.Codigo == ConfiguracionAPP.TipoContacto_Email ? "Por favor, ingrese mail" : "Por favor, ingrese teléfono") })
}

ProyectoAAPolo/AAPolo/Views/Jugador/_Domicilio.cshtml
@model AAPolo.Entities.Domicilio


@using (Html.BeginCollectionItem("lDomicilio"))
{
    @Html.HiddenFor(model => model.tipoDomicilio.Codigo)
    @Html.HiddenFor(model => model.Codigo)
    <div class="col-md-4">
        <label for="domicilio">Calle (opcional)</label>
        @Html.TextBoxFor(model => model.DireccionDomicilio@*, new { @class = "CampoRequerido", @data_textCampoRequerid = "Por favor, ingrese calle." }*@)
    </div>

    <div class="col-md-4">
        <label for="domicilio">Número (opcional)</label>
        @Html.TextBoxFor(model => model.NroDomicilio, new { @type = "number", @min = "0", @value= (Model.NroDomicilio == 0 ? "": Model.NroDomicilio.ToString()) })@*, @class = "CampoRequerido", @data_textCampoRequerid = "Por favor, ingrese número."*@
    </div>

    <div class="col-md-4">
        <label for="domicilio">Piso (opcional)</label>
        @Html.TextBoxFor(model => model.NroPiso, new { @type = "number", @min = "0" })
    </div>

    <div class="col-md-4">
        <label for="domicilio">Departamento (opcional)</label>
        @Html.TextBoxFor(model => model.Departamento)
    </div>

    <div class="col-md-4">
        <label for="domicilio">Código postal (opcional)</label>
        @Html.TextBoxFor(model => model.CodigoPostal)
    </div>

    <div class="col-md-4">
        <label for="domicilio">País de residencia</label>
        <select class="select2-basic PaisResidencia CampoRequerido" data-textCampoRequerid="Por favor, seleccione país de residencia." name="@Html.NameFor(model => model.pais.Codigo)" id="@Html.IdFor(model => model.pais.Codigo)">
            @Html.Action("_SelectPais", new { Cod_Pais = (Model.provincia != null && Model.pais.Codigo > 0 ? Model.pais.Codigo : 0) })
        </select>
    </div>

    <div class="col-md-4 ProvinciaResidencia" style="display:none">
        <label for="domicilio">Estado/Provincia</label>
        <select class="select2-basic ProvinciaResidencia" data-textCampoRequerid="Por favor, seleccione provincia de residencia." name="@Html.NameFor(model => model.provincia.Codigo)" id="@Html.IdFor(model => model.provincia.Codigo)">

            @if (Model.provincia != null && Model.provincia.Codigo > 0)
            {
                @Html.Action("_SelectProvincia", new { Codigo = Model.pais.Codigo, Cod_Provincia = Model.provincia.Codigo })
            }
            else
            {
                <option value="0" selected disabled>Seleccione provincia</option>
            }
        </select>
    </div>

    <div class="col-md-4 MunicipioResidencia" style="display:none">
        <label for="domicilio">Ciudad</label>
        <select class="select2-basic MunicipioResidencia" data-textCampoRequerid="Por favor, seleccione ciudad de residencia." name="@Html.NameFor(model => model.municipio.Codigo)" id="@Html.IdFor(model => model.municipio.Codigo)" style="display:none">
            @if (Model.municipio != null && Model.municipio.Codigo > 0)
            {
                @Html.Action("_SelectMunicipio", new { Codigo = Model.provincia.Codigo, Cod_Municipio = Model.municipio.Codigo })
            }
            else
            {
                <option value="0" selected disabled>Seleccione ciudad</option>
            }
        </select>
    </div>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectClub.cshtml
@model IEnumerable<AAPolo.Entities.Club>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(item.Codigo== ViewBag.Cod_ClubSelect ? "selected":"")>@item.NombreClub</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectGenero.cshtml
@model IEnumerable<AAPolo.Entities.Genero>


<option value="0" selected disabled>Seleccione género</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo">@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectJugadorHandicap.cshtml
@model IEnumerable<AAPolo.Entities.JugadorHandicap>
@using AAPolo.Entities
@{

    List<JugadorHandicap> lJug = Model.GroupBy(x => new { Jugador = x.tipoJugador.Codigo, Categoria = x.handicap.Categoria.Codigo }).Select(s => s.FirstOrDefault()).ToList();

 }


<option value="0" selected disabled>Seleccione un tipo de handicap</option>

@foreach (var item in lJug)
{
    <option value="@item.handicap.Codigo" >@item.tipoJugador.Nombre - @item.handicap.Categoria.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectMunicipio.cshtml
@model IEnumerable<AAPolo.Entities.Municipio>

<option value="0" @(ViewBag.Cod_Municipio == 0 ? "selected":"") disabled>Seleccione ciudad</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Cod_Municipio == item.Codigo ? "selected":"")>@item.Nombre</option>
}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectPais.cshtml
@model IEnumerable<AAPolo.Entities.Pais>


<option value="0" @(ViewBag.Cod_Pais == 0 ? "selected":"") disabled>Seleccione país</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Cod_Pais == item.Codigo ? "selected":"")>@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectPersona.cshtml
@model IEnumerable<AAPolo.Entities.Persona>


<option value="0" selected>Seleccione administador del club</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo">@item.NombreCompleto</option>
}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectProvincia.cshtml
@model IEnumerable<AAPolo.Entities.Provincia>


<option value="0" @(ViewBag.Cod_Provincia == 0 ? "selected":"") disabled>Seleccione provincia</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo" @(ViewBag.Cod_Provincia == item.Codigo ? "selected":"")>@item.Nombre</option>

}

ProyectoAAPolo/AAPolo/Views/Jugador/_SelectTipoDocumento.cshtml
@model IEnumerable<AAPolo.Entities.TipoDocumento>


<option value="0" selected disabled>Seleccione tipo de documento</option>

@foreach (var item in Model)
{
    <option value="@item.Codigo">@item.Nombre</option>

}